/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */

const { SES, SendEmailCommand } = require("@aws-sdk/client-ses");
const ses = new SES();
 
 exports.handler = async (event) => {
  if (event.request.userAttributes.email) {
    await sendTheEmail(
      event.request.userAttributes.email,
      `Hello ${event.userName}, this is an automated email generated by AWS Lambda following your verification.`
    );
  }
  return event;
};
 
const sendTheEmail = async (to, body) => {
  const eParams = {
    Destination: {
      ToAddresses: [to],
    },
    Message: {
      Body: {
        Text: {
          Data: body,
        },
      },
      Subject: {
        Data: "Cognito Identity Provider registration completed",
      },
    },
    Source: "james.matthew059@gmail.com",
  };
  try {
    await ses.send(new SendEmailCommand(eParams));
  } catch (err) {
    console.log(err);
  }
};